### ISSUE TITLE
Github Action doesn't work

### ISSUE THREAD

**Issue by frenklikapri** [n3wt0n/BugGuardian.MVC#2]
I watched your video about Github Actions with .NET Framework and tried it. I tried it also with your files and it shows this error. Can you please try it in your repository and see if this problem happens?

![image](https://user-images.githubusercontent.com/46903852/158886622-acbc6e5b-7b69-4399-8a47-b5822c21325a.png)

**Comment by n3wt0n** [comment]
Hey, yes that happens as you can see [here](https://github.com/n3wt0n/BugGuardian.MVC/runs/5594990753?check_suite_focus=true#step:6:42)

The reason is that .NET 4.5 (in my case) and .NET 4.6.1 are NOT installed anymore on the `windows-latest` hosted runners and you can see on the [official GitHub Doc](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md)

Until a while ago, `windows-latest` runners were running Windows 2019  but now they use Windows 2022 and older, out-of-support dependencies have been removed.

So you could either change the target framework to 4.6.2 or, as the exceptions says above, add a step to the workflow which would manually install the version of .NET SDK you need :)

**Comment by n3wt0n** [comment]
Just for completing the info, in the case of this very repo I changed the runners back to `windows-2019` because apart from .NET 4.5 not being present in the default 2022 image, there were 2 more problems:

- .NET 4.5 SDK cannot be installed on Windows 2022
- Visual Studio 2022, installed by default on `windows-latest` cannot build .NET 4.5 and 4.5.1 as stated [in the official MS documentation](https://docs.microsoft.com/en-us/dotnet/framework/install/guide-for-developers)

Now the build succeeds.

When and if GitHub will deprecate the `windows-2019` of the runners, I may need to upgrade the source code

**Comment by frenklikapri** [comment]
I understand it now. I also tried it and it worked. Thank you for the response
